
import __ASTRO_IMAGE_IMPORT_Z1V0nxw from "/src/images/a1-electrical/Alterations & Renovations.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Falterations-renovations.md";
import __ASTRO_IMAGE_IMPORT_ZDNaqX from "/src/images/a1-electrical/Electrical Inspections & Reports - 1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Felectrical-inspections.md";
import __ASTRO_IMAGE_IMPORT_2wHbjT from "/src/images/a1-electrical/Commercial Services - 1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fcommercial-electrical.md";
import __ASTRO_IMAGE_IMPORT_1B0ayV from "/src/images/a1-electrical/Electrical Rewiring & Switchboard Upgrades - 1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Felectrical-rewiring.md";
import __ASTRO_IMAGE_IMPORT_Z17Gs1T from "/src/images/a1-electrical/Heating, Ventilation & Heat Pump Installation - 1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fheat-pump-installation.md";
import __ASTRO_IMAGE_IMPORT_ntqbp from "/src/images/a1-electrical/New Builds.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fnew-builds.md";
import __ASTRO_IMAGE_IMPORT_Z6Dz1x from "/src/images/a1-electrical/General - 4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fpower-line-wraps.md";
import __ASTRO_IMAGE_IMPORT_1tpw9j from "/src/images/a1-electrical/Smart Home & Outdoor Solutions - 1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fsmart-home-outdoor.md";
export default new Map([["/src/images/a1-electrical/Alterations & Renovations.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Falterations-renovations.md", __ASTRO_IMAGE_IMPORT_Z1V0nxw], ["/src/images/a1-electrical/Electrical Inspections & Reports - 1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Felectrical-inspections.md", __ASTRO_IMAGE_IMPORT_ZDNaqX], ["/src/images/a1-electrical/Commercial Services - 1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fcommercial-electrical.md", __ASTRO_IMAGE_IMPORT_2wHbjT], ["/src/images/a1-electrical/Electrical Rewiring & Switchboard Upgrades - 1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Felectrical-rewiring.md", __ASTRO_IMAGE_IMPORT_1B0ayV], ["/src/images/a1-electrical/Heating, Ventilation & Heat Pump Installation - 1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fheat-pump-installation.md", __ASTRO_IMAGE_IMPORT_Z17Gs1T], ["/src/images/a1-electrical/New Builds.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fnew-builds.md", __ASTRO_IMAGE_IMPORT_ntqbp], ["/src/images/a1-electrical/General - 4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fpower-line-wraps.md", __ASTRO_IMAGE_IMPORT_Z6Dz1x], ["/src/images/a1-electrical/Smart Home & Outdoor Solutions - 1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fsmart-home-outdoor.md", __ASTRO_IMAGE_IMPORT_1tpw9j]]);
		